volumes:
  postgres_data:

services:
  postgres:
    container_name: project_customer_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: project_customer_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   container_name: project_customer_backend
  #   build:
  #     context: ./packages/project-customer-backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3333:3333"
  #   environment:
  #     PORT: 3333
  #     DATABASE_URL: postgres://admin:admin@postgres:5432/project_customer_postgres
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./packages/project-customer-backend:/app
  #     - /app/node_modules

  # frontend:
  #   container_name: project_customer_frontend
  #   build:
  #     context: ./packages/project-customer-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     NEXT_PUBLIC_BACKEND_URL: http://project_customer_backend:3333
  #   volumes:
  #     - ./packages/project-customer-frontend:/usr/src/app
  #     - /usr/src/app/node_modules
